function Test-TDTAdministrator {
    $id = [Security.Principal.WindowsIdentity]::GetCurrent()
    $p = New-Object Security.Principal.WindowsPrincipal($id)
    return $p.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Confirm-TDTAction { param([Parameter(Mandatory)][string]$Message); Write-Warning $Message; return ((Read-Host 'Confermi? [S/N]') -match '^[SsYy]') }
function Wait-TDTMenu { [void](Read-Host 'INVIO per continuare') }
function Get-TDTFolderSizeMB { param([Parameter(Mandatory)][string]$Path); if(-not(Test-Path -LiteralPath $Path)){return $null}; try{$sum=(Get-ChildItem -LiteralPath $Path -Force -File -Recurse -ErrorAction SilentlyContinue|Measure-Object Length -Sum).Sum;if($null-eq$sum){$sum=0};[math]::Round($sum/1MB,1)}catch{$null} }

function Invoke-TDTFlushDns { Write-Host "`n[RETE] Pulizia cache DNS..." -ForegroundColor Cyan; Clear-DnsClientCache -ErrorAction SilentlyContinue; & ipconfig.exe /flushdns }
function Restart-TDTNetworkAdapter { $a=@(Get-NetAdapter -Physical -ErrorAction SilentlyContinue|Where-Object Status -ne 'Disabled');if(-not$a){Write-Warning 'Nessuna scheda fisica attiva.';return};for($i=0;$i-lt$a.Count;$i++){Write-Host(" [{0}] {1} - {2}"-f($i+1),$a[$i].Name,$a[$i].Status)};$s=Read-Host 'Scheda (INVIO annulla)';if(-not$s){return};$n=0;if(-not[int]::TryParse($s,[ref]$n)-or$n-lt1-or$n-gt$a.Count){Write-Warning 'Scelta non valida.';return};$x=$a[$n-1];if(Confirm-TDTAction "Riavviare '$($x.Name)'? La connessione verra interrotta temporaneamente."){Restart-NetAdapter -Name $x.Name -Confirm:$false} }
function Set-TDTDnsPreset { $a=@(Get-NetAdapter -Physical -ErrorAction SilentlyContinue|Where-Object Status -eq 'Up');if(-not$a){Write-Warning 'Nessuna scheda con link attivo.';return};for($i=0;$i-lt$a.Count;$i++){Write-Host(" [{0}] {1}"-f($i+1),$a[$i].Name)};$s=Read-Host 'Scheda';$n=0;if(-not[int]::TryParse($s,[ref]$n)-or$n-lt1-or$n-gt$a.Count){return};$x=$a[$n-1];Write-Host ' [1] DHCP  [2] Cloudflare  [3] Google  [4] Quad9';switch(Read-Host 'Preset'){'1'{Set-DnsClientServerAddress -InterfaceIndex $x.ifIndex -ResetServerAddresses};'2'{Set-DnsClientServerAddress -InterfaceIndex $x.ifIndex -ServerAddresses '1.1.1.1','1.0.0.1'};'3'{Set-DnsClientServerAddress -InterfaceIndex $x.ifIndex -ServerAddresses '8.8.8.8','8.8.4.4'};'4'{Set-DnsClientServerAddress -InterfaceIndex $x.ifIndex -ServerAddresses '9.9.9.9','149.112.112.112'};default{return}};Clear-DnsClientCache -ErrorAction SilentlyContinue }
function Invoke-TDTNetworkCheck { Write-Host "`n[RETE] Diagnostica rapida" -ForegroundColor Cyan;$cfg=Get-NetIPConfiguration -ErrorAction SilentlyContinue|Where-Object{$_.IPv4Address-and$_.NetAdapter.Status-eq'Up'};foreach($c in $cfg){Write-Host("{0}: IP {1} Gateway {2} DNS {3}"-f$c.InterfaceAlias,$c.IPv4Address.IPAddress,$c.IPv4DefaultGateway.NextHop,($c.DNSServer.ServerAddresses-join','))};$g=($cfg|Where-Object IPv4DefaultGateway|Select-Object -First 1).IPv4DefaultGateway.NextHop;if($g){Write-Host("Gateway: {0}"-f$(if(Test-Connection $g -Count 1 -Quiet -ErrorAction SilentlyContinue){'OK'}else{'ERRORE'}))};Write-Host("Internet IP: {0}"-f$(if(Test-Connection '1.1.1.1' -Count 1 -Quiet -ErrorAction SilentlyContinue){'OK'}else{'ERRORE'}));try{Resolve-DnsName www.microsoft.com -Type A -ErrorAction Stop|Out-Null;Write-Host'DNS: OK'}catch{Write-Warning'DNS: ERRORE'} }
function Get-TDTNetworkAdvanced { Write-Host "`n[RETE] Diagnostica avanzata" -ForegroundColor Cyan;Get-NetAdapter -ErrorAction SilentlyContinue|Select-Object Name,Status,LinkSpeed,MacAddress,InterfaceDescription|Format-Table -AutoSize|Out-Host;Get-NetConnectionProfile -ErrorAction SilentlyContinue|Format-Table InterfaceAlias,Name,NetworkCategory,IPv4Connectivity -AutoSize|Out-Host;& netsh.exe winhttp show proxy;Get-NetTCPConnection -State Listen -ErrorAction SilentlyContinue|Sort-Object LocalPort|Select-Object -First 30 LocalAddress,LocalPort,OwningProcess|Format-Table -AutoSize|Out-Host }

function Test-TDTPendingReboot { foreach($p in @('HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootPending','HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired')){if(Test-Path$p){return$true}};return$false }
function Get-TDTWindowsUpdateStatus { Write-Host "`n[WINDOWS UPDATE] Stato" -ForegroundColor Cyan;Get-Service wuauserv,bits,UsoSvc,cryptsvc -ErrorAction SilentlyContinue|Format-Table Name,Status,StartType -AutoSize|Out-Host;Write-Host("Riavvio in sospeso: {0}"-f$(if(Test-TDTPendingReboot){'SI'}else{'NO'}));Get-HotFix -ErrorAction SilentlyContinue|Sort-Object InstalledOn -Descending|Select-Object -First 10 HotFixID,Description,InstalledOn|Format-Table -AutoSize|Out-Host }
function Find-TDTWindowsUpdates { Write-Host 'Ricerca aggiornamenti...' -ForegroundColor Cyan;$s=New-Object -ComObject Microsoft.Update.Session;$r=$s.CreateUpdateSearcher().Search('IsInstalled=0 and IsHidden=0');for($i=0;$i-lt$r.Updates.Count;$i++){Write-Host('- '+$r.Updates.Item($i).Title)};if($r.Updates.Count-eq0){Write-Host'Nessun aggiornamento disponibile.'-ForegroundColor Green} }
function Repair-TDTWindowsUpdateCache { if(-not(Confirm-TDTAction 'Rinominare SoftwareDistribution e catroot2 e rigenerare la cache Windows Update?')){return};$stamp=Get-Date -Format yyyyMMdd-HHmmss;try{'bits','wuauserv','cryptsvc'|ForEach-Object{Stop-Service $_ -Force -ErrorAction SilentlyContinue};$sd="$env:SystemRoot\SoftwareDistribution";$cr="$env:SystemRoot\System32\catroot2";if(Test-Path$sd){Rename-Item $sd "SoftwareDistribution.TDT-$stamp.old"};if(Test-Path$cr){Rename-Item $cr "catroot2.TDT-$stamp.old"}}finally{'cryptsvc','wuauserv','bits'|ForEach-Object{Start-Service $_ -ErrorAction SilentlyContinue}} }

function Invoke-TDTDismCheckHealth { & dism.exe /Online /Cleanup-Image /CheckHealth }
function Invoke-TDTDismScanHealth { & dism.exe /Online /Cleanup-Image /ScanHealth }
function Invoke-TDTDismRestoreHealth { if(Confirm-TDTAction 'Eseguire DISM /RestoreHealth?'){& dism.exe /Online /Cleanup-Image /RestoreHealth} }
function Invoke-TDTSfcScan { if(Confirm-TDTAction 'Eseguire SFC /scannow?'){& sfc.exe /scannow} }
function Invoke-TDTWindowsComponentRepair { if(Confirm-TDTAction 'Eseguire DISM /RestoreHealth seguito da SFC /scannow?'){& dism.exe /Online /Cleanup-Image /RestoreHealth;& sfc.exe /scannow} }

function Get-TDTDiskHealth { Write-Host "`n[DISCHI] Stato" -ForegroundColor Cyan;$d=@(Get-PhysicalDisk -ErrorAction SilentlyContinue);if($d){$d|Select-Object FriendlyName,MediaType,BusType,HealthStatus,OperationalStatus,@{N='SizeGB';E={[math]::Round($_.Size/1GB,1)}}|Format-Table -AutoSize|Out-Host}else{Get-CimInstance Win32_DiskDrive|Format-Table Model,InterfaceType,Status -AutoSize|Out-Host} }
function Invoke-TDTChkdskScan { $v=@(Get-Volume -ErrorAction SilentlyContinue|Where-Object{$_.DriveLetter-and$_.DriveType-eq'Fixed'});for($i=0;$i-lt$v.Count;$i++){Write-Host(" [{0}] {1}: {2}"-f($i+1),$v[$i].DriveLetter,$v[$i].FileSystemLabel)};$s=Read-Host 'Volume';$n=0;if([int]::TryParse($s,[ref]$n)-and$n-ge1-and$n-le$v.Count){& chkdsk.exe ("{0}:"-f$v[$n-1].DriveLetter) /scan} }
function Get-TDTPrinterStatus { Get-Printer -ErrorAction SilentlyContinue|Format-Table Name,DriverName,PortName,PrinterStatus -AutoSize|Out-Host;Get-Service Spooler|Format-Table Name,Status,StartType -AutoSize|Out-Host }
function Reset-TDTPrintSpooler { if(-not(Confirm-TDTAction 'Eliminare i documenti presenti nella coda di stampa?')){return};Stop-Service Spooler -Force;Get-ChildItem "$env:SystemRoot\System32\spool\PRINTERS" -Force -ErrorAction SilentlyContinue|Remove-Item -Force -ErrorAction SilentlyContinue;Start-Service Spooler }
function Get-TDTServiceHealth { Get-Service -ErrorAction SilentlyContinue|Where-Object{$_.StartType-eq'Automatic'-and$_.Status-eq'Stopped'}|Format-Table Name,DisplayName,Status,StartType -AutoSize|Out-Host;Write-Host 'Nota: alcuni servizi Automatici sono trigger-start.' -ForegroundColor Yellow }
function Restart-TDTServiceByName { $n=Read-Host 'Nome servizio';if(-not$n){return};$s=Get-Service $n -ErrorAction SilentlyContinue;if($s-and(Confirm-TDTAction "Riavviare $n?")){Restart-Service $n -Force} }
function Get-TDTDriverStatus { $b=@(Get-PnpDevice -ErrorAction SilentlyContinue|Where-Object Status -ne'OK');if($b){$b|Format-Table Status,Class,FriendlyName,InstanceId -Wrap -AutoSize|Out-Host}else{Write-Host'Nessun dispositivo PnP anomalo.'-ForegroundColor Green} }
function Invoke-TDTPnpRescan { if(Confirm-TDTAction 'Forzare nuova scansione Plug and Play?'){& pnputil.exe /scan-devices} }
function Get-TDTStartupItems { Get-CimInstance Win32_StartupCommand -ErrorAction SilentlyContinue|Format-Table Name,Location,User,Command -Wrap -AutoSize|Out-Host }
function Get-TDTRecentErrors { $st=(Get-Date).AddHours(-24);foreach($l in 'System','Application'){Write-Host"`n$l"-ForegroundColor Cyan;Get-WinEvent -FilterHashtable @{LogName=$l;Level=1,2;StartTime=$st} -MaxEvents 30 -ErrorAction SilentlyContinue|Select-Object TimeCreated,Id,ProviderName,Message|Format-Table -Wrap -AutoSize|Out-Host} }
function Get-TDTBitLockerStatus { if(Get-Command Get-BitLockerVolume -ErrorAction SilentlyContinue){Get-BitLockerVolume|Select-Object MountPoint,VolumeStatus,ProtectionStatus,EncryptionPercentage|Format-Table -AutoSize|Out-Host}else{& manage-bde.exe -status} }
function Get-TDTDiskSpaceReport { Get-Volume -ErrorAction SilentlyContinue|Where-Object DriveLetter|ForEach-Object{[pscustomobject]@{Volume="$($_.DriveLetter):";SizeGB=[math]::Round($_.Size/1GB,1);FreeGB=[math]::Round($_.SizeRemaining/1GB,1)}}|Format-Table -AutoSize|Out-Host;Write-Host("TEMP utente: {0} MB"-f(Get-TDTFolderSizeMB $env:TEMP)) }
function Get-TDTProcessTriage { Write-Host '[SICUREZZA] Triage processi - sola analisi' -ForegroundColor Cyan;$pf86=[Environment]::GetFolderPath('ProgramFilesX86');$items=foreach($p in Get-CimInstance Win32_Process -ErrorAction SilentlyContinue){if(-not$p.ExecutablePath){continue};$sig=Get-AuthenticodeSignature $p.ExecutablePath -ErrorAction SilentlyContinue;$score=0;$r=@();if(-not$sig-or$sig.Status-ne'Valid'){$score+=2;$r+='firma non valida/assente'};if($p.ExecutablePath-like"$env:TEMP\*"){$score+=3;$r+='TEMP'};if($score-ge2){[pscustomobject]@{Score=$score;PID=$p.ProcessId;Name=$p.Name;Signature=$sig.Status;Path=$p.ExecutablePath;Reasons=$r-join', '}}};$items|Sort-Object Score -Descending|Format-Table Score,PID,Name,Signature,Reasons -AutoSize|Out-Host;return@($items) }

function Show-TDTNetworkTools { do{Write-Host"`n--- RETE ---"-ForegroundColor Cyan;Write-Host' [1] Diagnostica rapida`n [2] Diagnostica avanzata`n [3] Pulisci DNS`n [4] Cambia DNS`n [5] Riavvia scheda`n [0] Indietro';$c=Read-Host'Scelta';switch($c){'1'{Invoke-TDTNetworkCheck};'2'{Get-TDTNetworkAdvanced};'3'{Invoke-TDTFlushDns};'4'{Set-TDTDnsPreset};'5'{Restart-TDTNetworkAdapter};'0'{return};default{continue}};Wait-TDTMenu}while($true) }
function Show-TDTWindowsUpdateTools { do{Write-Host"`n--- WINDOWS UPDATE ---"-ForegroundColor Cyan;Write-Host' [1] Stato`n [2] Cerca aggiornamenti`n [3] Ripara cache`n [0] Indietro';$c=Read-Host'Scelta';switch($c){'1'{Get-TDTWindowsUpdateStatus};'2'{Find-TDTWindowsUpdates};'3'{Repair-TDTWindowsUpdateCache};'0'{return};default{continue}};Wait-TDTMenu}while($true) }
function Show-TDTWindowsRepairTools { do{Write-Host"`n--- DISM / SFC ---"-ForegroundColor Cyan;Write-Host' [1] CheckHealth`n [2] ScanHealth`n [3] RestoreHealth`n [4] SFC /scannow`n [5] RestoreHealth + SFC`n [0] Indietro';$c=Read-Host'Scelta';switch($c){'1'{Invoke-TDTDismCheckHealth};'2'{Invoke-TDTDismScanHealth};'3'{Invoke-TDTDismRestoreHealth};'4'{Invoke-TDTSfcScan};'5'{Invoke-TDTWindowsComponentRepair};'0'{return};default{continue}};Wait-TDTMenu}while($true) }
function Show-TDTDiskTools { do{Write-Host"`n--- DISCHI ---"-ForegroundColor Cyan;Write-Host' [1] Stato / SMART`n [2] CHKDSK /scan`n [0] Indietro';$c=Read-Host'Scelta';switch($c){'1'{Get-TDTDiskHealth};'2'{Invoke-TDTChkdskScan};'0'{return};default{continue}};Wait-TDTMenu}while($true) }
function Show-TDTPrinterTools { do{Write-Host"`n--- STAMPANTI ---"-ForegroundColor Cyan;Write-Host' [1] Stato stampanti`n [2] Reset spooler`n [0] Indietro';$c=Read-Host'Scelta';switch($c){'1'{Get-TDTPrinterStatus};'2'{Reset-TDTPrintSpooler};'0'{return};default{continue}};Wait-TDTMenu}while($true) }
function Show-TDTServiceTools { do{Write-Host"`n--- SERVIZI ---"-ForegroundColor Cyan;Write-Host' [1] Controllo servizi`n [2] Riavvia servizio per nome`n [0] Indietro';$c=Read-Host'Scelta';switch($c){'1'{Get-TDTServiceHealth};'2'{Restart-TDTServiceByName};'0'{return};default{continue}};Wait-TDTMenu}while($true) }
function Show-TDTDriverTools { do{Write-Host"`n--- DRIVER ---"-ForegroundColor Cyan;Write-Host' [1] Dispositivi con problemi`n [2] Scansione PnP`n [0] Indietro';$c=Read-Host'Scelta';switch($c){'1'{Get-TDTDriverStatus};'2'{Invoke-TDTPnpRescan};'0'{return};default{continue}};Wait-TDTMenu}while($true) }

function Show-TDTTechnicianTools {
    param([string]$Root=(Split-Path -Parent $PSScriptRoot))
    if(-not(Test-TDTAdministrator)){throw'Gli Strumenti Tecnico richiedono privilegi amministrativi.'}
    do{
        Write-Host "`n=================================================="
        Write-Host ' TECNICO DIGITALE - STRUMENTI TECNICI' -ForegroundColor Cyan
        Write-Host '=================================================='
        Write-Host ' [1]  Rete'
        Write-Host ' [2]  Windows Update'
        Write-Host ' [3]  Integrita Windows - DISM / SFC'
        Write-Host ' [4]  Dischi / SMART / CHKDSK'
        Write-Host ' [5]  Stampanti'
        Write-Host ' [6]  Servizi'
        Write-Host ' [7]  Driver / dispositivi'
        Write-Host ' [8]  Avvio automatico (read-only)'
        Write-Host ' [9]  Eventi Windows recenti'
        Write-Host ' [10] BitLocker (read-only)'
        Write-Host ' [11] Spazio disco / TEMP (read-only)'
        Write-Host ' [12] Triage processi sospetti (read-only)'
        Write-Host ' [13] Comandi del tecnico - catalogo offline' -ForegroundColor Yellow
        Write-Host ' [0]  Torna al menu principale'
        $c=Read-Host'Scelta'
        try{switch($c){'1'{Show-TDTNetworkTools};'2'{Show-TDTWindowsUpdateTools};'3'{Show-TDTWindowsRepairTools};'4'{Show-TDTDiskTools};'5'{Show-TDTPrinterTools};'6'{Show-TDTServiceTools};'7'{Show-TDTDriverTools};'8'{Get-TDTStartupItems;Wait-TDTMenu};'9'{Get-TDTRecentErrors;Wait-TDTMenu};'10'{Get-TDTBitLockerStatus;Wait-TDTMenu};'11'{Get-TDTDiskSpaceReport;Wait-TDTMenu};'12'{Get-TDTProcessTriage|Out-Null;Wait-TDTMenu};'13'{if(Get-Command Show-TDTCommandReference -ErrorAction SilentlyContinue){Show-TDTCommandReference -Root $Root}else{Write-Warning'Modulo CommandReference non caricato.';Wait-TDTMenu}};'0'{return};default{Write-Warning'Scelta non valida.'}}}catch{Write-Warning $_.Exception.Message;Wait-TDTMenu}
    }while($true)
}
