[CmdletBinding()]
param([string]$Label = 'CURRENT')
Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'
function Safe([scriptblock]$s,$d=$null){try{& $s}catch{$d}}
function Prop($o,[string]$n,$d=''){if($null -eq $o){return $d};$p=$o.PSObject.Properties[$n];if($null -eq $p){return $d};$p.Value}
$reportDir=Join-Path $PSScriptRoot 'reports'; if(!(Test-Path $reportDir)){New-Item -ItemType Directory $reportDir -Force|Out-Null}
$os=Get-CimInstance Win32_OperatingSystem;$cs=Get-CimInstance Win32_ComputerSystem;$cpu=@(Get-CimInstance Win32_Processor)
$safeLabel=$Label-replace'[^A-Za-z0-9._-]','_';$safeComputer=$env:COMPUTERNAME-replace'[^A-Za-z0-9._-]','_';$stamp=Get-Date -Format 'yyyyMMdd-HHmmssfff';$unique=[guid]::NewGuid().ToString('N').Substring(0,8)
$outName="DeepAudit-$safeLabel-Build$($os.BuildNumber)-$safeComputer-$stamp-$unique.json";$outPath=Join-Path $reportDir $outName
Write-Host '=============================================================='
Write-Host ' TecnicoDigitale - Windows 11 Deep Audit (READ-ONLY)' -ForegroundColor Cyan
Write-Host '=============================================================='
Write-Host "Windows: $($os.Caption) - Build $($os.BuildNumber)";Write-Host "Computer: $env:COMPUTERNAME";Write-Host 'Nessuna impostazione verra modificata.';Write-Host ''
$processes=@(Get-Process|Sort-Object ProcessName,Id|ForEach-Object{[pscustomobject]@{Name=$_.ProcessName;Id=$_.Id;CPUSeconds=Safe {[math]::Round([double]$_.CPU,2)} 0;WorkingSetMB=[math]::Round($_.WorkingSet64/1MB,2);PrivateMemoryMB=[math]::Round($_.PrivateMemorySize64/1MB,2);HandleCount=Safe {$_.HandleCount};Path=Safe {$_.Path};Company=Safe {$_.Company}}})
$tasks=@();if(Get-Command Get-ScheduledTask -ErrorAction SilentlyContinue){$tasks=@(Get-ScheduledTask -ErrorAction SilentlyContinue|Sort-Object TaskPath,TaskName|ForEach-Object{[pscustomobject]@{TaskPath=[string]$_.TaskPath;TaskName=[string]$_.TaskName;State=[string]$_.State;Enabled=Safe {[bool]$_.Settings.Enabled} $false;Hidden=Safe {[bool]$_.Settings.Hidden} $false}})}
$appx=@();if(Get-Command Get-AppxPackage -ErrorAction SilentlyContinue){$appx=@(Get-AppxPackage -AllUsers -ErrorAction SilentlyContinue|Sort-Object Name,Version|ForEach-Object{[pscustomobject]@{Name=[string]$_.Name;Version=[string]$_.Version}})}
$prov=@();if(Get-Command Get-AppxProvisionedPackage -ErrorAction SilentlyContinue){$prov=@(Get-AppxProvisionedPackage -Online -ErrorAction SilentlyContinue|Sort-Object DisplayName|ForEach-Object{[pscustomobject]@{DisplayName=[string]$_.DisplayName;Version=[string]$_.Version}})}
$features=@();if(Get-Command Get-WindowsOptionalFeature -ErrorAction SilentlyContinue){$features=@(Get-WindowsOptionalFeature -Online -ErrorAction SilentlyContinue|ForEach-Object{[pscustomobject]@{FeatureName=[string]$_.FeatureName;State=[string]$_.State}})}
$caps=@();if(Get-Command Get-WindowsCapability -ErrorAction SilentlyContinue){$caps=@(Get-WindowsCapability -Online -ErrorAction SilentlyContinue|ForEach-Object{[pscustomobject]@{Name=[string]$_.Name;State=[string]$_.State}})}
$programs=@();foreach($u in @('HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*','HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*','HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*')){foreach($i in @(Get-ItemProperty $u -ErrorAction SilentlyContinue)){if($i.DisplayName){$programs+=[pscustomobject]@{DisplayName=[string]$i.DisplayName;DisplayVersion=[string]$i.DisplayVersion;Publisher=[string]$i.Publisher}}}};$programs=@($programs|Sort-Object DisplayName,DisplayVersion -Unique)
$startup=@(Get-CimInstance Win32_StartupCommand -ErrorAction SilentlyContinue|Sort-Object Name,Location|ForEach-Object{[pscustomobject]@{Name=[string]$_.Name;Command=[string]$_.Command;Location=[string]$_.Location;User=[string]$_.User}})
$services=@(Get-CimInstance Win32_Service|Sort-Object Name|ForEach-Object{[pscustomobject]@{Name=$_.Name;State=$_.State;StartMode=$_.StartMode;StartName=$_.StartName;PathName=$_.PathName}})
$total=[math]::Round($os.TotalVisibleMemorySize/1024,0);$free=[math]::Round($os.FreePhysicalMemory/1024,0);$edge=@($processes|Where-Object{$_.Name-match'^(msedge|msedgewebview2)$'})
$report=[ordered]@{SchemaVersion=4;AuditType='Windows11-Deep-Audit';GeneratedAt=(Get-Date).ToString('s');Label=$Label;ReportFileName=$outName;Computer=[ordered]@{ComputerName=$env:COMPUTERNAME;Manufacturer=$cs.Manufacturer;Model=$cs.Model;TotalRAMMB=[math]::Round($cs.TotalPhysicalMemory/1MB,0);Processor=@($cpu|ForEach-Object{$_.Name})};Windows=[ordered]@{Caption=$os.Caption;Version=$os.Version;BuildNumber=$os.BuildNumber;Architecture=$os.OSArchitecture;LastBootUpTime=Safe {([datetime]$os.LastBootUpTime).ToString('s')}};Snapshot=[ordered]@{ProcessCount=$processes.Count;TotalWorkingSetMB=[math]::Round((($processes|Measure-Object WorkingSetMB -Sum).Sum),2);TotalPrivateMemoryMB=[math]::Round((($processes|Measure-Object PrivateMemoryMB -Sum).Sum),2);PhysicalMemoryTotalMB=$total;PhysicalMemoryUsedMB=$total-$free;PhysicalMemoryFreeMB=$free;EnabledScheduledTasks=@($tasks|Where-Object Enabled).Count;InstalledAppxCount=$appx.Count;ProvisionedAppxCount=$prov.Count;EnabledFeatureCount=@($features|Where-Object State -eq 'Enabled').Count;InstalledCapabilityCount=@($caps|Where-Object State -eq 'Installed').Count;StartupItemCount=$startup.Count;RunningServiceCount=@($services|Where-Object State -eq 'Running').Count;EdgeWebViewProcessCount=$edge.Count;EdgeWebViewWorkingSetMB=[math]::Round((($edge|Measure-Object WorkingSetMB -Sum).Sum),2)};Processes=$processes;ScheduledTasks=$tasks;AppxInstalled=$appx;AppxProvisioned=$prov;OptionalFeatures=$features;Capabilities=$caps;InstalledPrograms=$programs;StartupItems=$startup;Services=$services}
$report|ConvertTo-Json -Depth 7|Set-Content $outPath -Encoding UTF8
Write-Host 'Riepilogo snapshot:' -ForegroundColor Cyan;Write-Host "  Processi             : $($report.Snapshot.ProcessCount)";Write-Host "  RAM fisica usata    : $($report.Snapshot.PhysicalMemoryUsedMB) MB / $total MB";Write-Host "  Startup item         : $($report.Snapshot.StartupItemCount)";Write-Host "  Servizi Running      : $($report.Snapshot.RunningServiceCount)";Write-Host "  AppX provisioned     : $($report.Snapshot.ProvisionedAppxCount)";Write-Host '';Write-Host "Report creato: $outPath" -ForegroundColor Green
